### ISSUE TITLE
rename no pide confirmación

### ISSUE THREAD

**Issue by maximoprieto** [hernanwilkinson/Cuis-Smalltalk-Refactoring#1]
Sería bueno que antes de hacer el rename, muestre los cambios a realizar y pida confirmación.

**Comment by ngarbezza** [comment]
@hernanwilkinson estoy usando la última versión y esto parece estar hecho ya 😄 

cc @maximoprieto

**Comment by hernanwilkinson** [comment]
Si, ya esta hecho
