### ISSUE TITLE
Rename method deja el metodo viejo en el panel de edición

### ISSUE THREAD

**Issue by ngarbezza** [hernanwilkinson/Cuis-Smalltalk-Refactoring#2]
Si estabas sobre el método que querés renombrar, una vez renombrado (sin problemas) queda la versión vieja en el panel del método (y nada seleccionado arriba)

Supongo que debería quedar la definición de la clase... o el método pero con el contenido nuevo.

**Comment by ngarbezza** [comment]
Adjunto un fix para esto. Para el rename method, muestra el selector nuevo. Para add/remove parameter lo "deselecciona" correctamente (porque me era un poco mas dificil obtener el "selector" nuevo)

Lo mando como .zip

[UnsavedChangesTo-Refactoring-RNG.1.cs.st.zip](https://github.com/hernanwilkinson/Cuis-Smalltalk-Refactoring/files/2500050/UnsavedChangesTo-Refactoring-RNG.1.cs.st.zip)

**Comment by hernanwilkinson** [comment]
Integrado en la ultima version, con nuevas cosas a tener en cuenta :-)
