### ISSUE TITLE
Error de falta de parentesis en Rename Temporary

### ISSUE THREAD

**Issue by ngarbezza** [hernanwilkinson/Cuis-Smalltalk-Refactoring#5]
Adjunto un gif que se explica mas claro:

![rename temporary bug](https://user-images.githubusercontent.com/519947/45253575-f89ab480-b33f-11e8-820d-806a5321724f.gif)

Parece que en ese caso consume mas caracteres de lo que debería.

Probado en versión #3426.

**Comment by hernanwilkinson** [comment]
Fixed no se en que version :-)
